name: Run
on:
  workflow_dispatch:
  pull_request_target:
  push:


jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Install dependencies
        run: pip3 install -r requirements.txt
      - name: Run
        run: python3 .
